name: SCDF AT Rabbit - env 2

on:
  workflow_dispatch:
    inputs:
      tests:
        type: string
        default: ''
        description: 'Test classes'
      cf-host:
        type: string
        default: ''
        description: 'CF host name (e.g. "bucharest")'
  workflow_call:
    inputs:
      tests:
        type: string
        default: ''
        description: 'Test classes'
    secrets:
      CF_USERNAME:
        required: true
      CF_ENV_0_PASSWORD:
        required: true
      CF_ENV_1_PASSWORD:
        required: true
      CF_ENV_2_PASSWORD:
        required: true
      SQL_USERNAME:
        required: false
      SQL_PASSWORD:
        required: false
      SQL_SYSTEM_USERNAME:
        required: false
      SQL_SYSTEM_PASSWORD:
        required: false
      SQL_HOST:
        required: false
      SQL_PORT:
        required: false
      KAFKA_USERNAME:
        required: false
      KAFKA_PASSWORD:
        required: false
      KAFKA_BROKER_ADDRESS:
        required: false

jobs:
  rabbit-2:
    uses: ./.github/workflows/at-common-workflow.yml
    with:
      cf_host: ${{ inputs.cf-host != '' && inputs.cf-host || 'vast-882596' }}
      cf_index: 2
      binder: rabbit
      tests: ${{ inputs.tests }}
    secrets:
      CF_USERNAME: ${{secrets.CF_USERNAME}}
      CF_ENV_0_PASSWORD: ${{secrets.CF_ENV_0_PASSWORD}}
      CF_ENV_1_PASSWORD: ${{secrets.CF_ENV_1_PASSWORD}}
      CF_ENV_2_PASSWORD: ${{secrets.CF_ENV_2_PASSWORD}}
      SQL_USERNAME: ${{secrets.SQL_USERNAME}}
      SQL_PASSWORD: ${{secrets.SQL_PASSWORD}}
      SQL_SYSTEM_USERNAME: ${{secrets.SQL_USERNAME}}
      SQL_SYSTEM_PASSWORD: ${{secrets.SQL_PASSWORD}}
      SQL_HOST: ${{secrets.SQL_HOST}}
      SQL_PORT: ${{secrets.SQL_PORT}}
